
services:
  # Servicio de la base de datos PostgreSQL
  postgres_db:
    image: postgres:15
    container_name: novafacts_postgres
    restart: always
    environment:
      POSTGRES_DB: novafacts_db
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de la aplicación Spring Boot
  spring_app:
    build: .
    container_name: novafacts_backend
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/novafacts_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
    depends_on:
      postgres_db:
        condition: service_healthy

# Volumen persistente para los datos de PostgreSQL
volumes:
  postgres_data:
