CREATE TABLE "rol" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "descripcion" text
);

CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "rol_id" int NOT NULL,
  "activo" boolean NOT NULL DEFAULT true,
  "creado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "canal" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "tipo" varchar(50) NOT NULL
);

CREATE TABLE "temporada" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date NOT NULL
);

CREATE TABLE "propiedad" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "direccion" text,
  "descripcion" text,
  "activa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "politica_cancelacion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "propiedad_id" int NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "descripcion" text,
  "activa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "regla_penalidad" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "politica_id" int NOT NULL,
  "tipo" varchar(50) NOT NULL,
  "valor" decimal(12,2) NOT NULL,
  "dias_anticipacion_min" int NOT NULL DEFAULT 0,
  "dias_anticipacion_max" int,
  "temporada_aplica" varchar(50)
);

CREATE TABLE "reserva" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "propiedad_id" int NOT NULL,
  "canal_id" int NOT NULL,
  "temporada_id" int,
  "politica_cancelacion_id" int NOT NULL,
  "usuario_creador_id" int NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date NOT NULL,
  "monto_total" decimal NOT NULL,
  "estado" varchar(50) NOT NULL,
  "no_show" boolean NOT NULL DEFAULT false,
  "creado_en" timestamp NOT NULL DEFAULT (now()),
  "modificado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "historial_reserva" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reserva_id" int NOT NULL,
  "usuario_id" int NOT NULL,
  "campo_modificado" varchar(100) NOT NULL,
  "valor_anterior" text,
  "valor_nuevo" text,
  "fecha_cambio" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "anticipo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reserva_id" int NOT NULL,
  "usuario_id" int NOT NULL,
  "monto" decimal(12,2) NOT NULL,
  "fecha_pago" date NOT NULL,
  "metodo_pago" varchar(80),
  "estado" varchar(50) NOT NULL,
  "registrado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "penalidad" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reserva_id" int NOT NULL,
  "usuario_id" int NOT NULL,
  "monto_segun_politica" decimal(12,2) NOT NULL,
  "monto_aprobado" decimal(12,2) NOT NULL,
  "monto_condonado" decimal(12,2) NOT NULL DEFAULT 0,
  "fecha_cancelacion" date NOT NULL,
  "motivo" text,
  "calculado_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "factura" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reserva_id" int NOT NULL,
  "usuario_id" int NOT NULL,
  "numero_factura" varchar(50) UNIQUE NOT NULL,
  "subtotal" decimal(12,2) NOT NULL,
  "descuento_anticipo" decimal(12,2) NOT NULL DEFAULT 0,
  "impuestos" decimal(12,2) NOT NULL DEFAULT 0,
  "total" decimal(12,2) NOT NULL,
  "estado" varchar(50) NOT NULL,
  "url_documento" text,
  "emitida_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "nota_credito" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "factura_id" int NOT NULL,
  "usuario_id" int NOT NULL,
  "numero_nota" varchar(50) UNIQUE NOT NULL,
  "monto" decimal(12,2) NOT NULL,
  "motivo" text,
  "emitida_en" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "devolucion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reserva_id" int NOT NULL,
  "anticipo_id" int NOT NULL,
  "usuario_id" int NOT NULL,
  "monto" decimal(12,2) NOT NULL,
  "metodo" varchar(80),
  "estado" varchar(50) NOT NULL,
  "generada_en" timestamp NOT NULL DEFAULT (now()),
  "procesada_en" timestamp
);

CREATE TABLE "log_transaccion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "entidad_afectada" varchar(80) NOT NULL,
  "entidad_id" int NOT NULL,
  "accion" varchar(50) NOT NULL,
  "datos_adicionales" json,
  "fecha_hora" timestamp NOT NULL DEFAULT (now())
);

COMMENT ON COLUMN "rol"."nombre" IS 'Administrador | Contador | Auxiliar contable | Recepcionista';

COMMENT ON COLUMN "canal"."nombre" IS 'Airbnb | Booking | Web propia | Teléfono | WhatsApp';

COMMENT ON COLUMN "canal"."tipo" IS 'externo | directo';

COMMENT ON COLUMN "regla_penalidad"."tipo" IS 'porcentaje | noches | valor_fijo | mixto';

COMMENT ON COLUMN "regla_penalidad"."dias_anticipacion_max" IS 'null = sin límite superior';

COMMENT ON COLUMN "regla_penalidad"."temporada_aplica" IS 'all | alta | baja — null = todas';

COMMENT ON COLUMN "reserva"."estado" IS 'pendiente | confirmada | cancelada | completada | no_show';

COMMENT ON COLUMN "anticipo"."metodo_pago" IS 'transferencia | tarjeta | efectivo | etc.';

COMMENT ON COLUMN "anticipo"."estado" IS 'registrado | aplicado | devuelto';

COMMENT ON COLUMN "penalidad"."monto_segun_politica" IS 'Penalidad calculada por la política (RF_09)';

COMMENT ON COLUMN "penalidad"."monto_aprobado" IS 'Penalidad aprobada finalmente (RF_09)';

COMMENT ON COLUMN "penalidad"."monto_condonado" IS 'Diferencia condonada (RF_09)';

COMMENT ON COLUMN "factura"."descuento_anticipo" IS 'Total anticipos descontados (RF_12)';

COMMENT ON COLUMN "factura"."estado" IS 'borrador | emitida | anulada';

COMMENT ON COLUMN "factura"."url_documento" IS 'Enlace factura electrónica (RF_14)';

COMMENT ON COLUMN "devolucion"."estado" IS 'pendiente | procesada | rechazada';

COMMENT ON COLUMN "log_transaccion"."entidad_afectada" IS 'reserva | factura | anticipo | penalidad | etc.';

COMMENT ON COLUMN "log_transaccion"."accion" IS 'crear | actualizar | eliminar | generar_factura | etc.';

ALTER TABLE "usuario" ADD FOREIGN KEY ("rol_id") REFERENCES "rol" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "politica_cancelacion" ADD FOREIGN KEY ("propiedad_id") REFERENCES "propiedad" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "regla_penalidad" ADD FOREIGN KEY ("politica_id") REFERENCES "politica_cancelacion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reserva" ADD FOREIGN KEY ("propiedad_id") REFERENCES "propiedad" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reserva" ADD FOREIGN KEY ("canal_id") REFERENCES "canal" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reserva" ADD FOREIGN KEY ("temporada_id") REFERENCES "temporada" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reserva" ADD FOREIGN KEY ("politica_cancelacion_id") REFERENCES "politica_cancelacion" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reserva" ADD FOREIGN KEY ("usuario_creador_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "historial_reserva" ADD FOREIGN KEY ("reserva_id") REFERENCES "reserva" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "historial_reserva" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anticipo" ADD FOREIGN KEY ("reserva_id") REFERENCES "reserva" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "anticipo" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "penalidad" ADD FOREIGN KEY ("reserva_id") REFERENCES "reserva" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "penalidad" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "factura" ADD FOREIGN KEY ("reserva_id") REFERENCES "reserva" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "factura" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "nota_credito" ADD FOREIGN KEY ("factura_id") REFERENCES "factura" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "nota_credito" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "devolucion" ADD FOREIGN KEY ("reserva_id") REFERENCES "reserva" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "devolucion" ADD FOREIGN KEY ("anticipo_id") REFERENCES "anticipo" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "devolucion" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "log_transaccion" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;
