-- V2__agregar_rol_y_restricciones.sql
-- Sprint 1: Create the rol reference table, seed the four business roles,
-- and enforce the FK constraint from usuario.rol_id to rol.id.

CREATE TABLE rol (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT
);

-- Insertion order determines the auto-generated IDs (1, 2, 3, 4).
-- The DevelopmentDataSeeder assigns rol_id=1 (Administrador) and rol_id=2 (Contador)
-- to existing seeded users, so this order must remain stable.
INSERT INTO rol (nombre, descripcion) VALUES
    ('Administrador',    'Control total del sistema: usuarios, propiedades, configuración'),
    ('Contador',         'Gestión financiera: anticipos, facturas, devoluciones'),
    ('Auxiliar contable','Apoyo contable: registro de reservas y anticipos'),
    ('Recepcionista',    'Atención al cliente: gestión de reservas y consultas');

ALTER TABLE usuario
    ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id) REFERENCES rol(id);
