-- V3__reference_data_y_correccion_propiedad.sql
-- Sprint 2: Correct the propiedad table to match Esquema_BD.sql,
-- create the canal reference table (seeded), and create the temporada table.

-- ── propiedad: add new columns ────────────────────────────────────────────────
ALTER TABLE propiedad ADD COLUMN descripcion TEXT;
ALTER TABLE propiedad ADD COLUMN activa BOOLEAN NOT NULL DEFAULT true;

-- Align direccion with schema: make it TEXT and nullable
ALTER TABLE propiedad ALTER COLUMN direccion TYPE TEXT USING direccion::TEXT;
ALTER TABLE propiedad ALTER COLUMN direccion DROP NOT NULL;

-- Drop the DB-level UNIQUE constraint on nombre (not in Esquema_BD)
ALTER TABLE propiedad DROP CONSTRAINT IF EXISTS propiedad_nombre_key;

-- ── propiedad: drop obsolete columns ─────────────────────────────────────────
-- WARNING: data in these columns is permanently deleted.
ALTER TABLE propiedad DROP COLUMN IF EXISTS ciudad;
ALTER TABLE propiedad DROP COLUMN IF EXISTS capacidad;
ALTER TABLE propiedad DROP COLUMN IF EXISTS precio_por_noche;
ALTER TABLE propiedad DROP COLUMN IF EXISTS creado_en;

-- ── canal ─────────────────────────────────────────────────────────────────────
CREATE TABLE canal (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(100) NOT NULL UNIQUE,
    tipo    VARCHAR(50)  NOT NULL
);

INSERT INTO canal (nombre, tipo) VALUES
    ('Airbnb',     'Plataforma'),
    ('Booking',    'Plataforma'),
    ('Web propia', 'Directo'),
    ('Teléfono',   'Directo'),
    ('WhatsApp',   'Directo');

-- ── temporada ─────────────────────────────────────────────────────────────────
CREATE TABLE temporada (
    id           INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL,
    fecha_inicio DATE         NOT NULL,
    fecha_fin    DATE         NOT NULL
);
