-- V4__reserva_rebuild_y_politica.sql
-- Sprint 3: Create politica_cancelacion table; rebuild reserva columns to match
-- Esquema_BD.sql (canal, temporada, politica, usuario_creador, client fields, monto_total);
-- eradicate huesped table permanently.

-- ── 1. politica_cancelacion ───────────────────────────────────────────────────
CREATE TABLE politica_cancelacion (
    id                   INT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    propiedad_id         BIGINT  NOT NULL,
    nombre               VARCHAR(150) NOT NULL,
    descripcion          TEXT,
    porcentaje_reembolso DECIMAL(5,2) NOT NULL,
    dias_aviso           INT NOT NULL,
    FOREIGN KEY (propiedad_id) REFERENCES propiedad(id)
);

-- ── 2. Clear stale reserva rows ────────────────────────────────────────────────
-- All existing rows reference huesped_id which will be invalid after huesped is
-- dropped. Truncating avoids FK bootstrap problems when adding NOT NULL columns
-- that reference canal / temporada / politica_cancelacion (which may be empty).
-- WARNING: this permanently deletes all existing reservation data.
TRUNCATE TABLE reserva RESTART IDENTITY;

-- ── 3. Drop obsolete huesped_id column ────────────────────────────────────────
ALTER TABLE reserva DROP COLUMN huesped_id;

-- ── 4. Add new columns (NOT NULL is safe — table is empty after TRUNCATE) ─────
ALTER TABLE reserva
    ADD COLUMN canal_id                 INT            NOT NULL,
    ADD COLUMN temporada_id             INT            NOT NULL,
    ADD COLUMN politica_cancelacion_id  INT            NOT NULL,
    ADD COLUMN usuario_creador_id       BIGINT         NOT NULL,
    ADD COLUMN cliente_nombre           VARCHAR(150)   NOT NULL,
    ADD COLUMN cliente_email            VARCHAR(150),
    ADD COLUMN cliente_telefono         VARCHAR(50),
    ADD COLUMN monto_total              DECIMAL(15,2)  NOT NULL;

-- ── 5. Foreign key constraints ────────────────────────────────────────────────
ALTER TABLE reserva
    ADD CONSTRAINT fk_reserva_canal
        FOREIGN KEY (canal_id) REFERENCES canal(id),
    ADD CONSTRAINT fk_reserva_temporada
        FOREIGN KEY (temporada_id) REFERENCES temporada(id),
    ADD CONSTRAINT fk_reserva_politica
        FOREIGN KEY (politica_cancelacion_id) REFERENCES politica_cancelacion(id),
    ADD CONSTRAINT fk_reserva_usuario
        FOREIGN KEY (usuario_creador_id) REFERENCES usuario(id);

-- ── 6. Eradicate huesped table ────────────────────────────────────────────────
-- CASCADE removes any remaining FK constraints that reference huesped.
DROP TABLE huesped CASCADE;
