-- V5__anticipos_penalidades_y_borrar_pagos.sql
-- Sprint 4: Create anticipo and penalidad tables (Esquema_BD.sql);
-- eradicate the invented pago table permanently.

-- ── 1. anticipo ────────────────────────────────────────────────────────────────
CREATE TABLE anticipo (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id    INT            NOT NULL,
    usuario_id    INT            NOT NULL,
    monto         DECIMAL(12,2)  NOT NULL,
    fecha_pago    DATE           NOT NULL,
    metodo_pago   VARCHAR(80),
    estado        VARCHAR(50)    NOT NULL,
    registrado_en TIMESTAMP      NOT NULL DEFAULT now(),
    FOREIGN KEY (reserva_id) REFERENCES reserva(id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- ── 2. penalidad ───────────────────────────────────────────────────────────────
CREATE TABLE penalidad (
    id                   INT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id           INT            NOT NULL,
    usuario_id           INT            NOT NULL,
    monto_segun_politica DECIMAL(12,2)  NOT NULL,
    monto_aprobado       DECIMAL(12,2)  NOT NULL,
    monto_condonado      DECIMAL(12,2)  NOT NULL DEFAULT 0,
    fecha_cancelacion    DATE           NOT NULL,
    motivo               TEXT,
    calculado_en         TIMESTAMP      NOT NULL DEFAULT now(),
    FOREIGN KEY (reserva_id) REFERENCES reserva(id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- ── 3. Eradicate pago ─────────────────────────────────────────────────────────
-- CASCADE removes any remaining FK constraints that reference pago.
DROP TABLE IF EXISTS pago CASCADE;
