-- V6__facturas_notas_y_devoluciones.sql
-- Sprint 5: Rebuild factura to match Esquema_BD.sql exactly (replace legacy iva/version/creado_en
-- with impuestos/descuento_anticipo/recargo_penalidad/usuario_id/numero_factura/emitida_en);
-- create nota_credito and devolucion tables.

-- ── 1. Rebuild factura ────────────────────────────────────────────────────────
-- Legacy factura has wrong columns (iva, version, creado_en) and missing FKs.
-- CASCADE removes any constraints pointing at the old table (e.g. old pago FK).
DROP TABLE IF EXISTS factura CASCADE;

CREATE TABLE factura (
    id                  INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id          INT           NOT NULL,
    usuario_id          INT           NOT NULL,
    numero_factura      VARCHAR(50)   NOT NULL UNIQUE,
    subtotal            DECIMAL(12,2) NOT NULL,
    descuento_anticipo  DECIMAL(12,2) NOT NULL DEFAULT 0,
    recargo_penalidad   DECIMAL(12,2) NOT NULL DEFAULT 0,
    impuestos           DECIMAL(12,2) NOT NULL DEFAULT 0,
    total               DECIMAL(12,2) NOT NULL,
    estado              VARCHAR(50)   NOT NULL,
    url_documento       TEXT,
    emitida_en          TIMESTAMP     NOT NULL DEFAULT now(),
    FOREIGN KEY (reserva_id) REFERENCES reserva(id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- ── 2. nota_credito ───────────────────────────────────────────────────────────
CREATE TABLE nota_credito (
    id           INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id   INT           NOT NULL,
    usuario_id   INT           NOT NULL,
    numero_nota  VARCHAR(50)   NOT NULL UNIQUE,
    monto        DECIMAL(12,2) NOT NULL,
    motivo       TEXT,
    emitida_en   TIMESTAMP     NOT NULL DEFAULT now(),
    FOREIGN KEY (factura_id) REFERENCES factura(id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- ── 3. devolucion ─────────────────────────────────────────────────────────────
CREATE TABLE devolucion (
    id           INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id   INT           NOT NULL,
    anticipo_id  INT           NOT NULL,
    usuario_id   INT           NOT NULL,
    monto        DECIMAL(12,2) NOT NULL,
    metodo       VARCHAR(80),
    estado       VARCHAR(50)   NOT NULL,
    generada_en  TIMESTAMP     NOT NULL DEFAULT now(),
    procesada_en TIMESTAMP,
    FOREIGN KEY (reserva_id)  REFERENCES reserva(id),
    FOREIGN KEY (anticipo_id) REFERENCES anticipo(id),
    FOREIGN KEY (usuario_id)  REFERENCES usuario(id)
);
