-- V7__fix_bigint_fk_types.sql
-- Fix: V5 and V6 declared primary-key and FK columns as INT while the referenced
-- columns (reserva.id, usuario.id) are BIGSERIAL (BIGINT).
-- PostgreSQL rejects creating a FK from INTEGER to BIGINT, so a clean install fails
-- starting at V5. V7 drops and recreates all five affected tables with BIGINT throughout.
-- Also adds UNIQUE on factura.reserva_id (one invoice per reservation, DB-level enforcement).
-- Note: existing rows in these tables are lost; run with dev profile to reseed via
-- DevelopmentDataSeeder (or execute "docker compose down -v && docker compose up -d").

-- ── 1. Drop all affected tables in reverse FK dependency order ────────────────
--    IF EXISTS guards handle the case where a prior migration failed mid-way.
DROP TABLE IF EXISTS devolucion    CASCADE;
DROP TABLE IF EXISTS nota_credito  CASCADE;
DROP TABLE IF EXISTS factura       CASCADE;
DROP TABLE IF EXISTS penalidad     CASCADE;
DROP TABLE IF EXISTS anticipo      CASCADE;

-- ── 2. anticipo ───────────────────────────────────────────────────────────────
CREATE TABLE anticipo (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id    BIGINT        NOT NULL,
    usuario_id    BIGINT        NOT NULL,
    monto         DECIMAL(12,2) NOT NULL,
    fecha_pago    DATE          NOT NULL,
    metodo_pago   VARCHAR(80),
    estado        VARCHAR(50)   NOT NULL,
    registrado_en TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT fk_anticipo_reserva FOREIGN KEY (reserva_id) REFERENCES reserva(id),
    CONSTRAINT fk_anticipo_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- ── 3. penalidad ──────────────────────────────────────────────────────────────
CREATE TABLE penalidad (
    id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id           BIGINT        NOT NULL,
    usuario_id           BIGINT        NOT NULL,
    monto_segun_politica DECIMAL(12,2) NOT NULL,
    monto_aprobado       DECIMAL(12,2) NOT NULL,
    monto_condonado      DECIMAL(12,2) NOT NULL DEFAULT 0,
    fecha_cancelacion    DATE          NOT NULL,
    motivo               TEXT,
    calculado_en         TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT fk_penalidad_reserva FOREIGN KEY (reserva_id) REFERENCES reserva(id),
    CONSTRAINT fk_penalidad_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- ── 4. factura ────────────────────────────────────────────────────────────────
--    reserva_id is UNIQUE: one invoice per reservation, enforced at the DB level.
CREATE TABLE factura (
    id                  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id          BIGINT        NOT NULL UNIQUE,
    usuario_id          BIGINT        NOT NULL,
    numero_factura      VARCHAR(50)   NOT NULL UNIQUE,
    subtotal            DECIMAL(12,2) NOT NULL,
    descuento_anticipo  DECIMAL(12,2) NOT NULL DEFAULT 0,
    recargo_penalidad   DECIMAL(12,2) NOT NULL DEFAULT 0,
    impuestos           DECIMAL(12,2) NOT NULL DEFAULT 0,
    total               DECIMAL(12,2) NOT NULL,
    estado              VARCHAR(50)   NOT NULL,
    url_documento       TEXT,
    emitida_en          TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT fk_factura_reserva FOREIGN KEY (reserva_id) REFERENCES reserva(id),
    CONSTRAINT fk_factura_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- ── 5. nota_credito ───────────────────────────────────────────────────────────
CREATE TABLE nota_credito (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factura_id   BIGINT        NOT NULL,
    usuario_id   BIGINT        NOT NULL,
    numero_nota  VARCHAR(50)   NOT NULL UNIQUE,
    monto        DECIMAL(12,2) NOT NULL,
    motivo       TEXT,
    emitida_en   TIMESTAMP     NOT NULL DEFAULT now(),
    CONSTRAINT fk_nota_credito_factura FOREIGN KEY (factura_id) REFERENCES factura(id),
    CONSTRAINT fk_nota_credito_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- ── 6. devolucion ─────────────────────────────────────────────────────────────
CREATE TABLE devolucion (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reserva_id   BIGINT        NOT NULL,
    anticipo_id  BIGINT        NOT NULL,
    usuario_id   BIGINT        NOT NULL,
    monto        DECIMAL(12,2) NOT NULL,
    metodo       VARCHAR(80),
    estado       VARCHAR(50)   NOT NULL,
    generada_en  TIMESTAMP     NOT NULL DEFAULT now(),
    procesada_en TIMESTAMP,
    CONSTRAINT fk_devolucion_reserva  FOREIGN KEY (reserva_id)  REFERENCES reserva(id),
    CONSTRAINT fk_devolucion_anticipo FOREIGN KEY (anticipo_id) REFERENCES anticipo(id),
    CONSTRAINT fk_devolucion_usuario  FOREIGN KEY (usuario_id)  REFERENCES usuario(id)
);
